#autoconfigure:
#  exclude: ${SPRING_AUTOCONFIGURE_EXCLUDE:org.springframework.boot.mongodb.autoconfigure.MongoAutoConfiguration,org.springframework.boot.data.mongodb.autoconfigure.DataMongoAutoConfiguration,org.springframework.boot.data.mongodb.autoconfigure.DataMongoRepositoriesAutoConfiguration}

spring:
  cache:
    type: redis

  security:
    user:
      name: disabled
      password: disabled
  application:
    name: payment-service

  datasource:
    url: jdbc:postgresql://payment-postgres:5432/uberdb-payments
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    rest:
      base-path: /api/data-rest
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      password: ${SPRING_DATA_REDIS_PASSWORD:redispass}


  mongodb:
    uri: ${SPRING_DATA_MONGODB_URI:mongodb://root:rootpass@localhost:27017/ubermongo?authSource=admin}

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: auto
        default-requeue-rejected: false
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3

server:
  port: 8080

feign:
  user-service:
    url: http://user-service:8080
  driver-service:
    url: http://driver-service:8080
  ride-service:
    url: http://ride-service:8080



jwt:
  secret: ${JWT_SECRET:dev-only-secret-change-me-32-chars-minimum-1234567890ABCDEF}
  expiration: ${JWT_EXPIRATION:86400000}
