apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: uber
spec:
  type: NodePort          # Makes it reachable from OUTSIDE the cluster
  selector:
    app: api-gateway
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080     # Access via: http://<minikube-ip>:30080
